<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<div class="bestseller-products-footer">

<h6><?php echo $this->getHeading(); ?></h6>

<?php $_productCollection=$this->getLoadedProductCollection() ?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
 	
	<?php $_collectionSize = $_productCollection->count() ?>
	
	<?php 
		$sliderFor = 10000;
		$productCount = $_collectionSize; 
	?>
	
	<?php if ($productCount >= $sliderFor): ?>
		<div class="customNavigation">
			<a class="btn prev">&nbsp;</a>
			<a class="btn next">&nbsp;</a>
		</div>	
	<?php endif; ?>	

		<ul class="<?php if ($productCount >= $sliderFor){?>product-carousel<?php }else{?>products-grid<?php }?>" id="<?php if ($productCount >= $sliderFor){?>bestseller-carousel<?php }else{?>bestseller-grid<?php }?>">
				
    	<?php $i=0; foreach ($_productCollection as $_product):  $i++;?>
		<?php if($i>3) break;?>
		<?php $_product = Mage::getModel('catalog/product')->load($_product->getEntityId()); ?>
		
           <li class="item <?php if ($productCount >= $sliderFor){?>slider-item<?php }else{?>product-items<?php }?>">
				<div class="product-block">
				<div class="product-block-inner">
					 <div class="product-image-block">
						<?php if($this->helper('framework')->isNewProduct($_product)):?>
							<div class="new-label"><?php echo $this->__('New') ?></div>
						<?php endif; ?>
						
						<?php if($this->helper('framework')->isSpecialProduct($_product)):?>
							<div class="sale-label"><?php echo $this->__('Sale') ?></div>
						<?php endif; ?>
						
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(50,50); ?>" width="50" height="50" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
						
				<div class="hover_block">
                   
				 <ul class="add-to-links">
				 <li>
				 		  <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>  
					</li>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('') ?></a></li>
                        <?php endif; ?>
                    </ul>                 
                </div>
		</div> <!--product-image-block end-->
				
				
				<div class="product_desc">
				<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>">
					<?php $str = strlen($this->escapeHtml($_product->getName()));
					
					if($str <=20 ){ 
					echo $this->escapeHtml($_product->getName()); ?>
					<?php }else{
					echo substr($this->escapeHtml($_product->getName()),0,20) ."..";
					
					}?>

				
				</a></h2>
				
                <?php echo $this->getPriceHtml($_product, true) ?>
				
				
								<div class="description grid_rating">
									<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
								</div>
							
						
            	</div>
				
				</div><!-- End div class product-block-->
				</div><!-- End div class product-block-inner -->
            </li>

        <?php endforeach ?>
		</ul>
		
		<span style="display: none; visibility: hidden;" class="footerbestseller_default_width"></span>
<?php endif; ?>

</div>