<script type="text/javascript">
    function hide_progress_popup(){
        document.getElementById("icecatlive_button_finish").remove();
        document.getElementById('icecatlive-response').innerHTML = '';
        $('loading-mask').setStyle({
            display: 'none'
        });
    }
    var error_limit = 0;

    function import_prod_info(update, full_import, error_import, process_hash){
        if(error_limit > 5){
          error_limit = 0;
          error_import = 0;
        }
        $('loading_mask_loader').setStyle({
            width: '430px',
            marginLeft: '-235px',
            top: '25%'
        });
        $('loading-mask').setStyle({
            opacity: '0.90'
        });
        $$('#loading_mask_loader > img')[0].setStyle({
            'display': 'inline'
        });
        new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/adminhtml_importproductinfo/check'); ?>', {
            method:     'get',
            parameters: {update: update, full_import: full_import, error_import: error_import, process_hash: process_hash},
            onSuccess: function(transport){
                var import_info = JSON.parse(transport.responseText);
                var count_products = '<p> Found products in shop: '+import_info.count_products+'</p>';
                var current_products = '<p> Current product: '+import_info.current_product+'</p>';
                var process_hash = 0;
                if(import_info.process_hash){
                  process_hash = import_info.process_hash
                }
                var error = '';
                var success_imported = '';
                var full_icecat_product = '';
                var error_imported = '';
                var system_error = '';
                if(import_info.error){
                    error = '<p class="icecatlive_error">'+import_info.error+'</p>';
                }
                var check_count_product = 0;
                if(import_info.success_imported_product){
                    check_count_product =  parseInt(check_count_product, 10)+parseInt(import_info.success_imported_product, 10);
                    success_imported = '<p> Imported information for products: '+import_info.success_imported_product+'</p>';
                }
                if(import_info.error_imported_product){
                    check_count_product =  parseInt(check_count_product)+parseInt(import_info.error_imported_product, 10);
                    error_imported = '<p> Did not imported information for products: '+import_info.error_imported_product+'</p>';
                }
                if(import_info.full_icecat_product){
                    full_icecat_product = '<p> Full icecat products: '+import_info.full_icecat_product+'</p>';
                }
                if(import_info.system_error){
                    system_error = '<p class="icecatlive_error"> System error: '+import_info.system_error+'</p>';
                }
                if(check_count_product > import_info.current_product){
                  current_products = '<p> Current product: '+check_count_product+'</p>';
                }
                if(import_info.done != 1){
                    if($('loading_mask_loader').select('#icecatlive-response').size() == 0){
                        $('loading_mask_loader').insert({bottom: '<div id="icecatlive-response" style="text-align: left">'
                            +count_products
                            +current_products
                            +success_imported
                            +full_icecat_product
                            +error_imported
                            +error
                            +system_error
                            +'</div>'});
                    }else{
                        $('icecatlive-response').replace('<div id="icecatlive-response" style="text-align: left">'
                            +count_products
                            +current_products
                            +success_imported
                            +full_icecat_product
                            +error_imported
                            +error
                            +system_error
                            +'</div>');
                    }
                    import_prod_info(update,0,0,process_hash);
                }else{
                    if($('loading_mask_loader').select('#icecatlive-response').size() == 0){
                        $('loading_mask_loader').insert({bottom: '<div id="icecatlive-response" style="text-align: left">'
                            +count_products
                            +current_products
                            +success_imported
                            +full_icecat_product
                            +error_imported
                            +error
                            +system_error
                            +'</div>'
                            +'<button id="icecatlive_button_finish" onclick="javascript:hide_progress_popup(); return false;" title="Finish import" type="button" class="scalable " style=""><span><span><span>Finish import</span></span></span></button>'});
                    }else{
                    $('icecatlive-response').replace('<div id="icecatlive-response" style="text-align: left">'
                        +count_products
                        +current_products
                        +success_imported
                        +full_icecat_product
                        +error_imported
                        +error
                        +system_error
                        +'</div>'
                        +'<button id="icecatlive_button_finish" onclick="javascript:hide_progress_popup(); return false;" title="Finish import" type="button" class="scalable " style=""><span><span><span>Finish import</span></span></span></button>');
                    }
                    $$('#loading_mask_loader > img')[0].setStyle({
                        'display': 'none'
                    });
                    var str = $('loading_mask_loader').innerHTML;
                    str = str.replace('<br>Please wait...', '');
                    $('loading_mask_loader').innerHTML = str;
                }
            },
            onComplete: function(){
                $('loading_mask').setStyle({
                    display: 'block'
                });
            },
            onFailure: function() {
              error_limit = error_limit + 1;
              setTimeout(function(){ import_prod_info(update,0,1); }, 500);
            }
        });
    }
    $('config_edit_form').on('change', '.input-text, .select', function(event) {
        if(!$('icecatlive-saveconfig')){
            $('icecatlive_button').writeAttribute('disabled', 'disabled');
            $('icecatlive_button').addClassName('disabled');
            $('icecatlive_button').insert({before: '<p id="icecatlive-saveconfig">Please save configuration, and after start import</p>'});
        }
    });

</script>
<?php echo $this->getButtonHtml(); ?>

