<?php $_problems = $this->getIcecatliveProblemsDigest(); ?>
<?php if(!empty($_problems) && is_array($_problems) && count($_problems) > 0):?>
<div class="notification-global" id="icecatlive-warning">
        <span class="f-right">
          <a href="<?php print $this->getManageUrl(); ?>" target="_blank"><?php echo $this->helper('icecatlive')->__('Go to system check section'); ?></a>
       </span>
            <strong class="label"><?php echo $this->helper( 'icecatlive' )->__( 'Warning' ); ?></strong>
            <?php echo $this->helper( 'icecatlive' )->__( "The Icecatlive extensions doesn't work properly, please go to configuration page and check the problems." ); ?>
</div>
<?php endif;?>