
   <!-- <div class="container tech">
        
              <div class="row">
                  
                  <?php if(count($this->getTech()) > 0):?>
                  
                   <?php foreach ($this->getTech() as $member): ?>
                  
                  
                    
                <?php if (($this->getDetails($member->getCustomerId())[2]) && (($this->getPackage($member->getMemberId()) == 1))): ?>
                <div class="col-md-3 col-sm-6">
                    <div class="our-team">
                        
                        <div class="team-content">
                           
                            <div class="pic"> 
                            <?php if(!$this->getDetails($member->getCustomerId())[1]):?>
                            <img alt="avatar" src="http://www.jainvivah.in/themes/site/images/d.png">
                            <?php else :?>
                            <img class="col-md-6" style="width:200px;border: 1px solid #eeeeee;"src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'customer/' . ltrim($this->getDetails($member->getCustomerId())[1], '/'); ?>" />
                            <?php endif;?>
                        </div>
                            <h3 class="post-title"><?php echo $member->getMemberName(); ?><small>Technician</small></h3>
                           <p class="description"><a class="btn btn-success" href="#myModal-<?php echo $member->getMemberId();?>">Get Details</a></p>
                        </div>
                    </div>
                </div>

                  
                  <div id="myModal-<?php echo $member->getMemberId();?>" class="overlay" style="z-index:100">
	<div class="popup">
            <div class="name"><h3><?php echo $member->getMemberName(); ?></h3></div>
		<a class="close" href="#">&times;</a>
		<div class="content">
 <div class="modal-body">
       <div class="row"><div class="col-md-3"><strong>Email</strong> </div> : <?php echo $member->getMemberEmail(); ?></div>
       <div class="row"><div class="col-md-3"><strong>Contact</strong></div> : <?php echo $this->getDetails($member->getCustomerId())[0]; ?></div>
      </div>		</div>
	</div>
</div>
                  
                  
                  
                  
<?php endif;?>
                 <?php endforeach; ?>
<?php else:?>
                  No registered Technicians available in this category
                  <?php endif;?>
                
            </div>
        </div>
    -->
    
   
        









<?php
/**
 * Hire A Technician
 *
 * @category      Sreedarsh
 * @package       Sreedarsh_Hat
 * @author Sreedarsh <sreedarsh88@gmail.com>
 */
?>   
    <br> 
    <div class="silver-tech">
     <ul class="product-carousel" id="featured-carosusel">        
			<?php foreach ($this->getTech() as $member): ?>    
                         <?php if (($this->getDetails($member->getCustomerId())[2]) && (($this->getPackage($member->getMemberId()) == 1))): ?>

            <li class="item slider-item" style="width:240px;">   
				  	<div class="product-block">
						<div class="product-block-inner">
				           <div class="product-image-block">
                                               <div style="min-height:250px;">
						 <?php if(!$this->getDetails($member->getCustomerId())[1]):?>
                                                   <a href="<?php echo Mage::getUrl('hireme/technician', array('id'=>$member->getCustomerId()));?>"> <img alt="avatar" src="http://www.jainvivah.in/themes/site/images/d.png"> </a>
                                             <?php else :?>
                                               	<a href="<?php echo Mage::getUrl('hireme/technician', array('id' => $member->getCustomerId()));?>" title="<?php echo $member->getMemberName(); ?>" class="product-image"><img  src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'customer/' . ltrim($this->getDetails($member->getCustomerId())[1], '/'); ?>" width="330" height="330" alt="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'customer/' . ltrim($this->getDetails($member->getCustomerId())[1], '/'); ?>" /></a>
						<?php endif;?>
						 </div>
                                                <div class="member-name" style="text-align: center;"> <h4><?php echo $member->getMemberName(); ?> </h4> </div>
                                                
						</div>  
							
					 </div>		
					</div>
					
               </li>  
               <?php endif;?>
               
    <?php endforeach; ?>
        </ul> 
</div>

 








        
    
    <style>
    .slider-item{
        width:240px !important;
    }
    
    .product-carousel .product-block{
        border-right: 1px solid #e4e4e4 !important;
    }
    </style>
