<?php
/**
 * Hire A Technician
 *
 * @category      Sreedarsh
 * @package       Sreedarsh_Hat
 * @author Sreedarsh <sreedarsh88@gmail.com>
 */
?>
    <div class="container tech">
        
        <h2 style="padding:20px 0;"> Hire a Technician </h2>
              <div class="row">
                  
                  <?php if(count($this->getTech()) > 0):?>
                  
                   <?php foreach ($this->getTech() as $member): ?>
                  
                  
                    
                  <?php if ($this->getDetails($member->getCustomerId())[2]): ?>
                <div class="col-md-3 col-sm-6">
                    <div class="our-team">
                        
                        <div class="team-content">
                            <?php if ($this->getPackage($member->getMemberId()) == 3): ?>
                            <div class="verified"><img src="<?php echo $this->getSkinUrl('images/verified.png') ?>" alt=""></div>
                            <?php endif;?>
                            <div class="pic"> 
                            <?php if(!$this->getDetails($member->getCustomerId())[1]):?>
                            <img alt="avatar" src="http://www.jainvivah.in/themes/site/images/d.png">
                            <?php else :?>
                            <img class="col-md-6" style="width:200px;border: 1px solid #eeeeee;"src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'customer/' . ltrim($this->getDetails($member->getCustomerId())[1], '/'); ?>" />
                            <?php endif;?>
                        </div>
                            <h3 class="post-title"><?php echo $member->getMemberName(); ?><small>Technician</small></h3>
                           <p class="description"><a class="btn btn-success" href="<?php echo Mage::getUrl('hireme/technician', array('id'=>$member->getCustomerId()));?>">Get Details</a></p>
                        </div>
                    </div>
                </div>

                  
                  
                  
                  <?php endif;?>
                  
                 <?php endforeach; ?>
<?php else:?>
                  No registered Technicians available
                  <?php endif;?>
                
            </div>
        </div>
    
    
    
        










