<?php
/**
 * Hire A Technician
 *
 * @category      Sreedarsh
 * @package       Sreedarsh_Hat
 * @author Sreedarsh <sreedarsh88@gmail.com>
 */
?>

<?php $technicians = $this->retriveTechlist();
$customer = Mage::getModel('customer/customer');
$tech = $this->getTech();
?>

    <div class="container tech">
        
        <h2 style="padding:20px 0;">Select a technician</h2>
              <div class="row">
                
                  <?php if(count($technicians) > 0):?>
                  
               <?php foreach($technicians as $user):
                   $member = $customer->load($user->getCustomerId());
                   ?>   
               <div class="col-md-3 col-sm-6">
                    <div class="our-team">
                        
                        <div class="team-content">                            
                            <div class="pic"> 
                            <?php if(!$member->getAvatar()):?>
                            <img alt="avatar" src="http://www.jainvivah.in/themes/site/images/d.png">
                            <?php else :?>
                            <img class="col-md-6" style="width:200px;border: 1px solid #eeeeee;"src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'customer/' . ltrim($member->getAvatar(), '/'); ?>" />
                            <?php endif;?>
                        </div>
                            <h3 class="post-title"><?php echo $member->getName(); ?><small>Technician</small></h3>
                           <p class="description"><a class="btn btn-success" href="<?php echo Mage::getUrl('hireme/technician', array('id'=>$member->getId()));?>">Get Details</a></p>
                        </div>
                    </div>
                </div> 
                 <?php endforeach;?> 
                  <?php else:?>
                  
                  No technicians available in this category
                  
                  <?php endif;?>
                
            </div>
        </div>
    
    
    
        










