
<?php
/**
 * Hire A Technician
 *
 * @category      Sreedarsh
 * @package       Sreedarsh_Hat
 * @author Sreedarsh <sreedarsh88@gmail.com>
 */
?>   


<?php $customer = $this->customer();
$technician = $this->retriveAllTech();
?>

<?php if($technician->count() >=1):?>
   
<div class="w3-content w3-display-container">
    <?php foreach($technician as $tech):?>
    <?php $pic = $customer->load($tech->getCustomerId());?>
    <?php if($pic->getAvatar() && $pic->getVerifiedMember()):?>
 
    <a href="<?php echo Mage::getUrl('hireme/technician', array('id'=>$tech->getCustomerId()));?>"><img class="mySlides" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'customer/' . ltrim($pic->getAvatar(), '/'); ?>" style="width:100%"><a>
  
        <?php endif;?>

  <?php  endforeach;?>
  <a class="w3-btn-floating w3-display-left" onclick="plusDivs(-1)">&#10094;</a>
  <a class="w3-btn-floating w3-display-right" onclick="plusDivs(1)">&#10095;</a>
</div>

<?php else:?>

<img src="<?php echo $this->getSkinUrl('images/banners/sub_banner4.jpg',array('_secure'=>true)); ?>" class="my-img" />

<?php endif;?>

<script>
var slideIndex = 1;
showDivs(slideIndex);

function plusDivs(n) {
  showDivs(slideIndex += n);
}

function showDivs(n) {
  var i;
  var x = document.getElementsByClassName("mySlides");
  if (n > x.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = x.length}
  for (i = 0; i < x.length; i++) {
     x[i].style.display = "none";  
  }
  x[slideIndex-1].style.display = "block";  
}
</script>


<a href="<?php echo Mage::getUrl('hireme/technician/category/');?>><button type="submit" title="View" class="button"><span><span>View all</span></span></button> </a>