<?php
/**
 * Hire A Technician
 *
 * @category      Sreedarsh
 * @package       Sreedarsh_Hat
 * @author Sreedarsh <sreedarsh88@gmail.com>
 */
?>   

<script src="https://cdnjs.cloudflare.com/ajax/libs/bxslider/4.2.5/jquery.bxslider.min.js"></script>
<style>
/* bxslider */
.bx-wrapper {
  position: relative;
  left: 50%;
  transform: translateX(-50%);
  padding: 0;
  *zoom: 1;
}

.bx-wrapper img {
  max-width: 100%;
  display: block;
  margin-bottom: 0px;
}
.bx-wrapper p {
    text-align: center;
    margin: 4px 2px 5px 2px;
}

/** THEME
===================================*/
/*.bxslider {
  top: -12px;
}*/


.bx-wrapper .bx-pager{
  display: none;
}

.bx-wrapper .bx-controls-auto {
  position: absolute;
  bottom: -30px;
  width: 100%;
}

/* LOADER */

.bx-wrapper .bx-loading {
  min-height: 50px;
  background: url(//bxslider.com/lib/images/bx_loader.gif) center center no-repeat #fff;
  height: 100%;
  width: 100%;
  position: absolute;
  top: 0;
  left: 0;
  z-index: 2000;
}

.bx-wrapper .bx-controls-auto .bx-controls-auto-item {
  display: inline-block;
  *zoom: 1;
  *display: inline;
}

/* DIRECTION CONTROLS (NEXT / PREV) */

.bx-wrapper .bx-prev {
  left: -15px;  
  border-radius: 15px;
}

.bx-wrapper .bx-prev:before{
  content:'';
background: url(https://www.japonshop.com/css/img/flch-izq.gif) no-repeat center;  
  width: 20px;
  height: 20px;
  position: absolute;
  left: 50%;
  top: 50%;  
  transform: translate(-50%, -50%);
}

.bx-wrapper .bx-next {
  right: -15px; 
  border-radius: 15px;  
}

.bx-wrapper .bx-next:before{
  content:'';
background: url(https://www.japonshop.com/css/img/flch-der.gif) no-repeat center; 
  width: 20px;
  height: 20px;
  position: absolute;
  left: 50%;
  top: 50%;  
  transform: translate(-50%, -50%);
}

.bx-wrapper .bx-controls-direction a {  
  position: absolute;
  top: 50%;
  transform:translateY(-50%);
  outline: 0;
  width: 32px;
  height: 32px; 
  text-indent: -9999px;
  z-index: 9999;
  border: 1px solid #e6e6e6;
background: -webkit-linear-gradient(#fcfcfc 0%, #ebebeb 100%);
background: -moz-linear-gradient(#fcfcfc 0%, #ebebeb 100%);
background: -o-linear-gradient(#fcfcfc 0%, #ebebeb 100%);
background: linear-gradient(#fcfcfc 0%, #ebebeb 100%);  
}

.bx-wrapper .bx-controls-direction a:hover{
  background: #ebebeb;
}

.bx-wrapper .bx-controls-direction a:hover:before{
  left:45%;
}

.bx-wrapper .bx-controls-direction a.bx-next:hover:before{
  left:55%;
}


.bx-wrapper .bx-controls-direction a.disabled {
  display: none;
}

/* AUTO CONTROLS (START / STOP) */

.bx-wrapper .bx-controls-auto {
  text-align: center;
}

.bx-wrapper .bx-controls-auto .bx-start {
  display: block;
  text-indent: -9999px;
  width: 10px;
  height: 11px;
  outline: 0;
  background: url(//bxslider.com/lib/images/controls.png) -86px -11px no-repeat;
  margin: 0 3px;
}

.bx-wrapper .bx-controls-auto .bx-start:hover,
.bx-wrapper .bx-controls-auto .bx-start.active {
  background-position: -86px 0;
}

.bx-wrapper .bx-controls-auto .bx-stop {
  display: block;
  text-indent: -9999px;
  width: 9px;
  height: 11px;
  outline: 0;
  background: url(//bxslider.com/lib/images/controls.png) -86px -44px no-repeat;
  margin: 0 3px;
}

.bx-wrapper .bx-controls-auto .bx-stop:hover,
.bx-wrapper .bx-controls-auto .bx-stop.active {
  background-position: -86px -33px;
}

/* PAGER WITH AUTO-CONTROLS HYBRID LAYOUT */

.bx-wrapper .bx-controls.bx-has-controls-auto.bx-has-pager .bx-pager {
  text-align: left;
  width: 80%;
}

.bx-wrapper .bx-controls.bx-has-controls-auto.bx-has-pager .bx-controls-auto {
  right: 0;
  width: 35px;
}

/* IMAGE CAPTIONS */

.bx-wrapper .bx-caption {
  position: absolute;
  bottom: 0;
  left: 0;
  background: #666\9;
  background: rgba(80, 80, 80, 0.75);
  width: 100%;
}

.bx-wrapper .bx-caption span {
  color: #fff;
  font-family: Arial;
  display: block;
  font-size: .85em;
  padding: 10px;
}
</style>
<script>
var $k =jQuery.noConflict();
$k(document).ready(function(){

$k('.bxslider').bxSlider({
  minSlides: 2,
  maxSlides: 2,
  slideWidth: 150,
  slideMargin: 20,
  auto: true,
});
});
</script>
<?php $customer = $this->customer();
$technician = $this->retriveAllTech();
?>


   
 <?php foreach($technician as $tech):?>
 
<?php $tech_array[] =  $tech->getCustomerId();?>

  <?php  endforeach;?>

<?php if($technician->count() >=1):?>
   
<div class="w3-content w3-display-container">
    <div class="bxslider">
    <div>
        <?php $tech0 = $customer->load($tech_array[0]);$avatar0 = $tech->getAvatarImage()?>
        <a href="<?php echo Mage::getUrl('hireme/technician', array('id'=>$tech_array[0]));?>"> <img src="<?php if($avatar0) { echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'customer/' . ltrim($tech0->getAvatarImage(), '/');}else{ echo $this->getSkinUrl('images/dummy.jpg');} ?>" /> </a>
      <p><?php echo $tech0->getName();?></p>
      <p><?php echo ($this->getCatname($tech0->getMemberCategory()) != "")?$this->getCatname($tech0->getMemberCategory()):'&nbsp;';?></p>
      
      <?php $customer->unsetData();?>
      <?php $tech1 = $customer->load($tech_array[1]); $avatar1 = $tech1->getAvatarImage()?>
      <a href="<?php echo Mage::getUrl('hireme/technician', array('id'=>$tech_array[1]));?>"> <img src="<?php if($avatar1) { echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'customer/' . ltrim($tech1->getAvatarImage(), '/');}else{ echo $this->getSkinUrl('images/dummy.jpg');} ?>" /> </a>
      <p><?php echo $tech1->getName();?></p>
      <p><?php echo ($this->getCatname($tech1->getMemberCategory()) != "")?$this->getCatname($tech1->getMemberCategory()):'&nbsp;';?></p>
      <?php $customer->unsetData();?>
    </div>
        
    <div>
        <?php $tech2 = $customer->load($tech_array[2]); $avatar2 = $tech2->getAvatarImage()?>
        <a href="<?php echo Mage::getUrl('hireme/technician', array('id'=>$tech_array[2]));?>"> <img src="<?php if($avatar2) { echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'customer/' . ltrim($tech2->getAvatarImage(), '/'); }else{ echo $this->getSkinUrl('images/dummy.jpg');}?>" /> </a>
      <p><?php echo $tech2->getName();?></p>
      <p><?php echo ($this->getCatname($tech2->getMemberCategory()) != "")?$this->getCatname($tech2->getMemberCategory()):'&nbsp;';?></p>
      <?php $customer->unsetData();?>
      <?php $tech3 = $customer->load($tech_array[3]); $avatar3 = $tech3->getAvatarImage()?>
      <a href="<?php echo Mage::getUrl('hireme/technician', array('id'=>$tech_array[3]));?>"><img src="<?php if($avatar3) { echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'customer/' . ltrim($tech3->getAvatarImage(), '/'); }else{ echo $this->getSkinUrl('images/dummy.jpg');}?>" /> </a>
      <p><?php echo $tech3->getName();?></p>
      <p><?php echo ($this->getCatname($tech3->getMemberCategory()) != "")?$this->getCatname($tech3->getMemberCategory()):'&nbsp;';?></p>
      <?php $customer->unsetData();?>
    </div>
        
     <?php if($technician->count() > 4):?>
   
    <div>
        <?php $tech4 = $customer->load($tech_array[4]); $avatar4 = $tech4->getAvatarImage()?>
        <a href="<?php echo Mage::getUrl('hireme/technician', array('id'=>$tech_array[4]));?>"> <img src="<?php if($avatar4) { echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'customer/' . ltrim($tech4->getAvatarImage(), '/');}else{ echo $this->getSkinUrl('images/dummy.jpg');} ?>" /> </a>
      <p><?php echo $tech4->getName();?></p>
      <p><?php echo ($this->getCatname($tech4->getMemberCategory()) !="")?$this->getCatname($tech4->getMemberCategory()):'&nbsp;';?></p>
      <?php $customer->unsetData(); ?>
      <?php $tech5 = $customer->load($tech_array[5]); $avatar5 = $tech5->getAvatarImage()?>
      <a href="<?php echo Mage::getUrl('hireme/technician', array('id'=>$tech_array[5]));?>"> <img src="<?php if($avatar5) { echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'customer/' . ltrim($tech5->getAvatarImage(), '/'); }else{ echo $this->getSkinUrl('images/dummy.jpg');}?>" /> </a>
      <p><?php echo $tech5->getName();?></p>
      <p><?php echo ($this->getCatname($tech5->getMemberCategory()) != "")?$this->getCatname($tech5->getMemberCategory()):'&nbsp;';?></p>    
      <?php $customer->unsetData();?>
    </div>
        
    <div>
        <?php $tech6 = $customer->load($tech_array[6]); $avatar6 = $tech6->getAvatarImage()?>
        <a href="<?php echo Mage::getUrl('hireme/technician', array('id'=>$tech_array[6]));?>">  <img src="<?php if($avatar6) { echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'customer/' . ltrim($tech6->getAvatarImage(), '/');}else{ echo $this->getSkinUrl('images/dummy.jpg');} ?>" /> </a>
      <p><?php echo $tech6->getName();?></p>
      <p><?php echo ($this->getCatname($tech6->getMemberCategory()) != "")?$this->getCatname($tech6->getMemberCategory()):'&nbsp;';?></p>
      <?php $customer->unsetData();?>
      
      <?php $tech7 = $customer->load($tech_array[7]); $avatar7 = $tech7->getAvatarImage()?>
      <a href="<?php echo Mage::getUrl('hireme/technician', array('id'=>$tech_array[7]));?>"> <img src="<?php if($avatar7) {echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'customer/' . ltrim($tech7->getAvatarImage(), '/');}else{ echo $this->getSkinUrl('images/dummy.jpg');} ?>" /> </a>
      <p><?php echo $tech7->getName();?></p>
      <p><?php echo ($this->getCatname($tech7->getMemberCategory()) != "")?$this->getCatname($tech7->getMemberCategory()):'&nbsp;';?></p>
      <?php $customer->unsetData();?>
    </div>
        
      <?php endif;?>  
  
  </div>
</div>

<?php else:?>

<img src="<?php echo $this->getSkinUrl('images/banners/sub_banner4.jpg',array('_secure'=>true)); ?>" class="my-img" />

<?php endif;?>


<a href="<?php echo Mage::getUrl('hireme/technician/category/');?>" class="hireprof-viewall">View all</a>