<?php
/**
 * @category     Inchoo
 * @package     Inchoo Featured Products
 * @author        Domagoj Potkoc, Inchoo Team <web@inchoo.net>
 * @modified    Mladen Lotar <mladen.lotar@surgeworks.com>, Vedran Subotic <vedran.subotic@surgeworks.com>
 */
?>
 <div class="featured-products">
<div class="category-title"><h2><?php echo $this->__($this->getBlockLabel()) ?></h2></div>

<?php if(!$this->getProductCollection()->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?> 
<?php if (($_productCollection = $this->getProductCollection()) && $_productCollection->getSize()): ?>
 
	<?php // Grid Mode ?>
    <?php $_collectionSize = $_productCollection->count() ?>
 	
		<?php 
		$sliderFor = 5;
		$productCount = $_collectionSize; 
	?>
	<?php if ($productCount >= $sliderFor): ?>
		<div class="customNavigation">
			<a class="btn prev">&nbsp;</a>
			<a class="btn next">&nbsp;</a>
		</div>	
	<?php endif; ?>	

        <ul class="<?php if ($productCount >= $sliderFor){?>product-carousel<?php }else{?>products-grid<?php }?>" id="<?php if ($productCount >= $sliderFor){?>featured-carousel<?php }else{?>featured-grid<?php }?>">
            
			<?php  $i = 0; $row = 0; foreach ($_productCollection->getItems() as $_product):  ?>
            
			      <li class="item <?php if ($productCount >= $sliderFor){?>slider-item<?php }else{?>product-items<?php }?>">   
				  	<div class="product-block">
						<div class="product-block-inner">
				           <div class="product-image-block">
						<?php if($this->helper('framework')->isNewProduct($_product)):?>
							<div class="new-label"><?php echo $this->__('New') ?></div>
						<?php endif; ?>
						
						<?php if($this->helper('framework')->isSpecialProduct($_product)):?>
							<div class="sale-label"><?php echo $this->__('Sale') ?></div>
						<?php endif; ?>
					 
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(330,330); ?>" width="330" height="330" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
						
						
						</div>  <!--product-image-block end-->
						<div class="hover_block">
 								
								 <ul class="add-to-links">
								 <li>
								 <?php if ($_product->isSaleable()): ?>
                                    <button type="button" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span><em><span class="pattern"></span>Add to Cart</em></button>
                                <?php else: ?>
                                    <div class="out-of-stock"><?php echo $this->__('Out of stock') ?></div>
                                <?php endif; ?>
								</li>
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><em><span class="pattern"></span>Add to Wishlist</em><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('') ?></a></li>
										<?php endif; ?>
										<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
											<li><em><span class="pattern"></span>Add to Compare</em><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('') ?></a></li>
										<?php endif; ?>
									</ul>
							</div>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_product->getName()) ?>)">
                            <?php $str = strlen($this->escapeHtml($_product->getName()));
					
					if($str <= 25 ){ 
					echo $this->escapeHtml($_product->getName()); ?>
					<?php }else{
					echo substr($this->escapeHtml($_product->getName()),0,25) ."..";
				
				}?></a></h2>
							
							<?php echo $this->getPriceHtml($_product, true, '-new') ?>
							
							
								<div class="description grid_rating">
									<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
								</div>
							
					 </div><!-- End div class product-block-inner -->		
					</div><!-- End div class product-block-->
					
               </li>        
    <?php endforeach; ?>
        </ul> 
</div>
<span class="featured_default_width" style="display:none; visibility:hidden"></span>
<?php endif; ?>
<?php endif; ?>
 