<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct();?>
<?php if($_additionalgroup = $this->getAdditionalData()): ?>
<div class="box-collateral box-additional">
    <?php $i=0; foreach ($_additionalgroup as $_additional): $i++; ?>
    <h3><?php if(!empty($_additional['title'])){ echo $this->__( $_additional['title'] ); }?></h3>
        <table class="data-table" id="product-attribute-specs-table-<?php echo $i?>">
            <col width="25%" />
            <col />
            <tbody>
            <?php foreach ($_additional['items'] as $_data): ?>
<?php if($_data['label'] != 'Specification'):?>
                <tr>
                    <th class="label"><?php echo $this->htmlEscape($this->__($_data['label'])) ?></th>
                    <td class="data"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                </tr>
<?php endif; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('product-attribute-specs-table-<?php echo $i?>')</script>
    <?php endforeach; ?>

</div>
<script type="text/javascript">
//script which starts after page is loaded
jQuery(document).ready(function (jQuery) {
      jQuery.ajax({ crossDomain : true, url: "<?php echo $this->getIcecatStatisticsUrl($_product); ?>"});
});
</script>
<?php endif;?>



